name: Deploy Python project to Azure Function App v2

# on:
#   [push]

on:
  push:
    branches:
      - main

env:
  AZURE_FUNCTIONAPP_NAME: azfunc255980 # set this to your application's name
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'azure-function/python'   # set this to the path to your web app project, defaults to the repository root
  PYTHON_VERSION: '3.9'                 # set this to the python version to use (supports 3.9)

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # runs-on: ubuntu-18.04
    steps:

    - name: Checkout GitHub Action
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Install Azure CLI
      run: |
        curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
      shell: bash

    - name: Login to Azure
      run: |
        az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}
      shell: bash

    - name: Install Python
      run: |
        sudo apt-get update
        sudo apt-get install -y python3.9
      shell: bash

    # ORIGINAL
    # - name: Install dependencies
    #   run: |
    #     python -m venv .venv
    #     source .venv/bin/activate
    #     python -m pip install -r requirements.txt
    #     echo "" > requirements.txt # blank out requirements.txt so it doesn't get installed again
    #   working-directory: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}

    # TENTATIVA 1
    - name: Install dependencies
      run: |
        python -m venv .venv
        source .venv/bin/activate
        python -m pip install -r requirements.txt        
      working-directory: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}

    # TENTATIVA 2   
    - name: Install dependencies v2
      run: |
        pip install --target="./.python_packages/lib/site-packages" -r ./requirements.txt
      working-directory: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}

    - name: Install library using npm
      run: |
        npm install -g azure-functions-core-tools

    - name: Deploy to Azure
      run: |
        func azure functionapp publish ${{ env.AZURE_FUNCTIONAPP_NAME }} --python
      shell: bash
      working-directory: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}